apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "github-scaffolding.labels" . | nindent 4 }}
spec:
  project: {{ .Values.argocd.application.project | default "default" }}
  source:
    repoURL: {{ include "github-scaffolding.toRepoUrl" . }}
    targetRevision: {{ .Values.git.toRepo.branch }}
    path: {{ .Values.argocd.application.source.path }}
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: {{ .Values.argocd.application.destination.namespace }}
    {{- /* Safely read flags with defaults */ -}}
    {{- $globallyPaused := dig "global" "globallyPaused" false .Values -}}
    {{- $syncEnabled   := dig "argocd" "application" "syncEnabled" false .Values -}}

    {{- if $globallyPaused }}
    syncPolicy: {}
    {{- else if $syncEnabled }}
    syncPolicy:
      automated:
        prune: {{ dig "argocd" "application" "syncPolicy" "automated" "prune" false .Values }}
        selfHeal: {{ dig "argocd" "application" "syncPolicy" "automated" "selfHeal" false .Values }}
      syncOptions:
        - CreateNamespace=true
    {{- else }}
    syncPolicy: {}
    {{- end }}


