apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "github-scaffolding.labels" . | nindent 4 }}
spec:
  project: {{ .Values.argocd.application.project | default "default" }}
  source:
    repoURL: {{ include "github-scaffolding.toRepoUrl" . }}
    targetRevision: {{ .Values.git.toRepo.branch }}
    path: {{ .Values.argocd.application.source.path }}
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: {{ .Values.argocd.application.destination.namespace }}
  {{- if and (hasKey .Values.global "globallyPaused") .Values.global.globallyPaused }}
  syncPolicy: {}
  {{- else if .Values.argocd.application.syncEnabled }}
  syncPolicy:
    automated:
      prune: {{ default false .Values.argocd.application.syncPolicy.automated.prune }}
      selfHeal: {{ default false .Values.argocd.application.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
  {{- else }}
  syncPolicy: {}
  {{- end }}
