{{- $global := .Values.global | default (dict) }}

{{- $group := $global.compositionGroup | default "" }}
{{- $version := $global.compositionInstalledVersion | default "" }}
{{- $kind := $global.compositionKind | default "" }}
{{- $namespace := $global.compositionNamespace | default "" }}
{{- $name := $global.compositionName | default "" }}

{{- $cr := nil }}
{{- if and $group $version $kind }}
  {{- $gv := printf "%s/%s" $group $version }}
  {{- $cr = lookup $gv $kind $namespace $name }}
{{- end }}
apiVersion: github.kog.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ .Release.Name }}-repo
  labels:
    {{- include "frontend-github-scaffolding.labels" . | nindent 4 }}
  annotations:
    krateo.io/connector-verbose: "{{ .Values.git.toRepo.verbose }}"
    krateo.io/deletion-policy: {{ .Values.git.toRepo.deletionPolicy | lower }}
    {{- if $cr }}
    {{- $annotations := $cr.metadata.annotations | default dict }}
    {{- if or (not (hasKey $annotations "krateo.io/paused")) (ne (index $annotations "krateo.io/paused") "true") }}
    krateo.io/paused: "true"
    {{- else }}
    krateo.io/paused: "false"
    {{- end }}
    {{- end }}
spec:
  authenticationRefs:
    bearerAuthRef: bearer-github-ref
  org: {{ .Values.git.toRepo.org }}
  name: {{ .Values.git.toRepo.name }}
  private: {{ .Values.git.toRepo.private }}
  auto_init: {{ .Values.git.toRepo.initialize }}
